language: node_js
node_js:
- '5'
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: De8nW1k+K04j4h21niC2mUyF1oAa72FsIgEpZ5qsZgu/VL6dCD62TjRLuj7vPrU3YNosGNfipMGdWOSGZahRZfAHUBIKHDVsK3p9RRemm568C3516WcHLHUKpzTtKCWUnst3imN1bMwy3Lm5AjQqpIipz0XR5ZvYBjNattZPtNC3dQDVvx16ya7AGIFlTOJ1WfGzicjiwrcG29OT7C0d8XgThNF4Rd5NWtNZoAEqkNppVXW2S8cjsFVugYNqUxcSUnP7elWW6NtmHuNTRYN+gSjZae7Wlbe1i2Q4ZQ4aZtbrwuCVk2fKjcLwiVxURRxXTol6Nr0FGvGt5KmgbrtE2yhIlinkDSrqWWATCO8XjX+xbFFpaMEKLvSjVuPLp6Io8irmzyza3P/KCKEOUIRZjQJO5hEJgVQOWbyQN9xjKktlOqdK2ddIEtnHHeHt9PHRjfWDVUPaYveQQRmweftdQafT8XVlYZ61rPSLr2GX+FnAtd4fpGkdoTqGET5CWf92frUFUdsUvwcncobAgmr0a4accJ+4Z4ZBmgrG/WzIzkHBSdCOMmxGUF/r3vDk33ZitYYVOmq/oBKwdqUN6eUUt2Pgo0WtJF2u3HIxgl/VdqLiU67HCi7Lef7O+NBftdxmDFHI8XzHTBI2D8yUblb8bTIbJovF6wUQg2Mnd2PAKVc=
  on:
    tags: true
    branches: true
